baseURL = "https://cours.hadrienpelissier.fr/"
languageCode = "fr-FR"
title = "Formations Uptime"
theme = ["hugo-theme-learn", "reveal-hugo"]

# Pour la fonctionnalité de recherche
[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
editURL = "https://github.com/ketsapiwiq/hp_cursus_devops"
globalTitle = "Kubernetes - Janvier 2021"

# [menu.shortcuts]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true