baseURL = "https://cours.hadrienpelissier.fr/"
languageCode = "fr-FR"
title = "Docker - Novembre 2020"

# Modifiez le thème pour qu'il soit utilisé par défaut à chaque génération de site.
theme = "hugo-theme-learn"

# Pour la fonctionnalité de recherche
[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
editURL = "https://github.com/ketsapiwiq/hp_cursus_devops"


# [menu.shortcuts]