baseURL = "https://cursus-janvier2020.uptime-formation.fr/"
languageCode = "fr-FR"
title = "Formation Ansible"
theme = ["hugo-theme-learn", "reveal-hugo"]


# Pour la fonctionnalité de recherche
[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
editURL = "https://github.com/e-lie/hugo_cursus_janvier2020"


# [menu.shortcuts]


[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true